--------------------------------------------------------
--  Fichier créé - jeudi-novembre-11-2021   
--------------------------------------------------------
DROP TABLE "MEHDI"."RECEVOIR";
DROP TABLE "MEHDI"."VOITURE";
DROP TABLE "MEHDI"."SERVICE";
DROP TABLE "MEHDI"."FACTURE";
DROP TABLE "MEHDI"."EMPLOYE";
DROP TABLE "MEHDI"."CLIENT";
DROP TABLE "MEHDI"."CARTE_FIDELITE";
--------------------------------------------------------
--  DDL for Table RECEVOIR
--------------------------------------------------------

  CREATE TABLE "MEHDI"."RECEVOIR" 
   (	"NOM_SERVICE" VARCHAR2(20 BYTE), 
	"MATRICULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOITURE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."VOITURE" 
   (	"MATRICULE" NUMBER, 
	"MARQUE" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"COULEUR" VARCHAR2(20 BYTE), 
	"DATE_AJOUT" DATE, 
	"CIN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."SERVICE" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"COUT" FLOAT(126), 
	"DUREE" NUMBER(*,0), 
	"DISPONIBILITE" BLOB, 
	"ID_EMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DISPONIBILITE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."FACTURE" 
   (	"NUM" NUMBER, 
	"DATE_FACTURATION" DATE, 
	"CIN_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."EMPLOYE" 
   (	"ID" NUMBER, 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER, 
	"NOM_S" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "MEHDI"."CLIENT" 
   (	"CIN" NUMBER(*,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"MATRICULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CARTE_FIDELITE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."CARTE_FIDELITE" 
   (	"NUM" NUMBER, 
	"POINTS" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MEHDI.RECEVOIR
SET DEFINE OFF;
REM INSERTING into MEHDI.VOITURE
SET DEFINE OFF;
Insert into MEHDI.VOITURE (MATRICULE,MARQUE,MODELE,COULEUR,DATE_AJOUT,CIN) values ('1472','ford','focus','rouge',to_date('01/06/20','DD/MM/RR'),'123');
Insert into MEHDI.VOITURE (MATRICULE,MARQUE,MODELE,COULEUR,DATE_AJOUT,CIN) values ('4567','peugot','classe s','rouge',null,'123');
Insert into MEHDI.VOITURE (MATRICULE,MARQUE,MODELE,COULEUR,DATE_AJOUT,CIN) values ('7894','qdsf','i8','bleu',to_date('09/11/21','DD/MM/RR'),'123');
REM INSERTING into MEHDI.SERVICE
SET DEFINE OFF;
REM INSERTING into MEHDI.FACTURE
SET DEFINE OFF;
REM INSERTING into MEHDI.EMPLOYE
SET DEFINE OFF;
REM INSERTING into MEHDI.CLIENT
SET DEFINE OFF;
Insert into MEHDI.CLIENT (CIN,NOM,PRENOM,ADRESSE,TELEPHONE,MATRICULE) values ('123','aze','ret','aze','789',null);
REM INSERTING into MEHDI.CARTE_FIDELITE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RECEVOIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."RECEVOIR_PK" ON "MEHDI"."RECEVOIR" ("MATRICULE", "NOM_SERVICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_VOITURE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."PK_VOITURE" ON "MEHDI"."VOITURE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."SERVICE_PK" ON "MEHDI"."SERVICE" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."TABLE1_PK" ON "MEHDI"."FACTURE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."EMPLOYE_PK" ON "MEHDI"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."PK_CLIENT" ON "MEHDI"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CARTE_FIDELITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."CARTE_FIDELITE_PK" ON "MEHDI"."CARTE_FIDELITE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECEVOIR
--------------------------------------------------------

  ALTER TABLE "MEHDI"."RECEVOIR" ADD CONSTRAINT "RECEVOIR_PK" PRIMARY KEY ("MATRICULE", "NOM_SERVICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."RECEVOIR" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."RECEVOIR" MODIFY ("NOM_SERVICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."VOITURE" MODIFY ("COULEUR" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."VOITURE" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."VOITURE" MODIFY ("MARQUE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."VOITURE" ADD CONSTRAINT "PK_VOITURE" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."VOITURE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."SERVICE" MODIFY ("ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."SERVICE" ADD CONSTRAINT "SERVICE_PK" PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."SERVICE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."SERVICE" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."SERVICE" MODIFY ("DUREE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."FACTURE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."FACTURE" MODIFY ("CIN_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."FACTURE" MODIFY ("DATE_FACTURATION" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."FACTURE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."EMPLOYE" MODIFY ("NOM_S" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."EMPLOYE" MODIFY ("FONCTION" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "MEHDI"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."CLIENT" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARTE_FIDELITE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."CARTE_FIDELITE" ADD CONSTRAINT "CARTE_FIDELITE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."CARTE_FIDELITE" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."CARTE_FIDELITE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."CARTE_FIDELITE" MODIFY ("POINTS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RECEVOIR
--------------------------------------------------------

  ALTER TABLE "MEHDI"."RECEVOIR" ADD CONSTRAINT "RECEVOIR_FK_01" FOREIGN KEY ("NOM_SERVICE")
	  REFERENCES "MEHDI"."SERVICE" ("NOM") ENABLE;
  ALTER TABLE "MEHDI"."RECEVOIR" ADD CONSTRAINT "RECEVOIR_FK_02" FOREIGN KEY ("MATRICULE")
	  REFERENCES "MEHDI"."VOITURE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."VOITURE" ADD CONSTRAINT "VOITURE_FK" FOREIGN KEY ("CIN")
	  REFERENCES "MEHDI"."CLIENT" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."SERVICE" ADD CONSTRAINT "SERVICE_FK" FOREIGN KEY ("ID_EMP")
	  REFERENCES "MEHDI"."EMPLOYE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."FACTURE" ADD CONSTRAINT "FACTURE_FK" FOREIGN KEY ("CIN_CLIENT")
	  REFERENCES "MEHDI"."CLIENT" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_FK" FOREIGN KEY ("NOM_S")
	  REFERENCES "MEHDI"."SERVICE" ("NOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "MEHDI"."CLIENT" ADD CONSTRAINT "CLIENT_FK" FOREIGN KEY ("MATRICULE")
	  REFERENCES "MEHDI"."VOITURE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARTE_FIDELITE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."CARTE_FIDELITE" ADD CONSTRAINT "CARTE_FIDELITE_FK" FOREIGN KEY ("ID")
	  REFERENCES "MEHDI"."CLIENT" ("CIN") ENABLE;
